---
name: Upload removed to R2

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - removed.json

env:
  VERSION: "v1"
  DEFAULT_PYTHON: "3.13"

concurrency:
  group: upload-removed
  cancel-in-progress: true

jobs:
  upload-removed:
    name: Generate removed metadata
    runs-on: ubuntu-latest
    steps:
      - name: ‚§µÔ∏è Check out code
        uses: actions/checkout@v4.2.2

      - name: Validate with JSON schema
        uses: cardinalby/schema-validator-action@3.1.1
        with:
          file: removed.json
          schema: tools/jsonschema/removed.schema.json

      - name: Process Removed File
        run: |
          mkdir -p output/removed
          jq -c . < removed.json > output/removed/data.json
          jq -c '[.[].repository]' < removed.json > output/removed/repositories.json

      - name: Upload metadata Artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: removed
          path: output/removed
          if-no-files-found: error
          retention-days: 7

  publish:
    name: Publish removed metadata
    runs-on: ubuntu-latest
    needs: upload-removed
    environment:
      name: removed
    steps:
      - name: ‚§µÔ∏è Check out code
        uses: actions/checkout@v4.2.2

      - name: üèó Set up UV
        uses: astral-sh/setup-uv@v4.2.0
        with:
          version: "latest"
          python-version: ${{ env.DEFAULT_PYTHON }}
          enable-cache: true

      - name: üèó Install project dependencies
        run: uv sync --no-group dev

      - name: ‚§µÔ∏è Download artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          name: removed
          path: output

      - name: ‚§¥Ô∏è Upload data to Cloudflare R2
        run: |
          uv run aws s3 sync \
            output \
            s3://rotorhazard-plugins/${{ env.VERSION }}/removed \
            --endpoint-url=${{ secrets.CF_R2_ENDPOINT }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CF_R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CF_R2_SECRET_ACCESS_KEY }}

      - name: Bust Cloudflare cache
        run: |
          curl --silent --show-error --fail -X POST \
            "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CF_BUST_CACHE_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"files": [
              "https://rh-data.dutchdronesquad.nl/${{ env.VERSION }}/removed/data.json",
              "https://rh-data.dutchdronesquad.nl/${{ env.VERSION }}/removed/repositories.json"
            ]}'
